### ISSUE TITLE
Support python 3.13

### ISSUE THREAD

**Issue by robbievanleeuwen** [m-clare/cytriangle#9]
Hi @m-clare, I'm wondering if there's much work in adding builds for python 3.13? I'm looking at adding python 3.13 support to `sectionproperties` soon :)

Thanks,
Robbie

**Comment by m-clare** [comment]
@robbievanleeuwen Just tried this out. Of course everything passed except Windows build 3.13 😅 .

I'll take a closer look tomorrow, but it looks like there's an `access violation`.

**Comment by robbievanleeuwen** [comment]
If it's `numpy` related you may need `numpy>=2.1.0`, as this is when [official support](https://numpy.org/news/#numpy-210-released) started?

**Comment by robbievanleeuwen** [comment]
Just saw your `dev` branch - you're all over it 😄

**Comment by m-clare** [comment]
@robbievanleeuwen just published 2.0.0 on PyPI (dropping 3.9 support is a breaking change).

**Comment by robbievanleeuwen** [comment]
Hi @m-clare, just a heads up that the latest version of PyPI is v1.0.4 whereas the latest GItHub tag is v2.0.0.

**Comment by m-clare** [comment]
> Hi @m-clare, just a heads up that the latest version of PyPI is v1.0.4 whereas the latest GItHub tag is v2.0.0.

Thanks. There seems to be an issue with the publish GitHub action vs CI, so I'm still trying to figure out why it's tagging all the builds as 1.0.4
